### ISSUE TITLE
Additional names for KCHA cleanup

### ISSUE THREAD

**Issue by alastairmatheson** [PHSKC-APDE/Housing#23]
https://github.com/PHSKC-APDE/Housing/blob/f266ac795d2534ee3b7a5b39c5ca8450b5b787e2/etl/stage/load_stage_kcha.R#L541

There are additional institutional/filler names that need cleaning:
lname = "PLH SITE", fname = "HEADSTART"
lname = "& GIRLS CLUB, fname = "SW BRANCH BO"

**Comment by dcolombara** [comment]
Confirmed in SQL that issue has been fixed.
