### ISSUE TITLE
False SSNs to clean

### ISSUE THREAD

**Issue by alastairmatheson** [PHSKC-APDE/Housing#24]
Both KCHA and SHA data have SSN values of '111223333' which should be cleaned out:
https://github.com/PHSKC-APDE/Housing/blob/f266ac795d2534ee3b7a5b39c5ca8450b5b787e2/etl/stage/load_stage_kcha.R#L573
https://github.com/PHSKC-APDE/Housing/blob/main/etl/stage/load_stage_sha.R#L247

**Comment by dcolombara** [comment]
updated validate_ssn function to address this. Still need to apply the function to the KCHA and SHA data.

**Comment by alastairmatheson** [comment]
Also found '123121234' in case that's not in the function

**Comment by dcolombara** [comment]
`validate_ssn` should clean both 123121234 & 111223333 and the function has been added to both the stage_kcha and stage_sha R scripts. Stage tables have been completely rebuilt, this issue has been addressed (confirmed by checking data in SQL)
