### ISSUE TITLE
License

### ISSUE THREAD

**Issue by arokem** [PHSKC-APDE/Housing#3]
Could we add a license to this code? This is important because it tells potential users outside of our two groups how they might be allowed to use the code (see: http://www.astrobetter.com/blog/2014/03/10/the-whys-and-hows-of-licensing-scientific-code/). 

@alastairmatheson : are there any restrictions on how you can license the code? All else being equal, I think that we would be the happiest with a BSD or MIT license (see aformentioned blog post for reasons why we would prefer these licenses).

**Comment by alastairmatheson** [comment]
The description file refers to a GPL-3 license, however I don't know if there was a licence file to go with it. I'm ok with changing to MIT and adding the file.

**Comment by arokem** [comment]
Thanks! Done in #4

**Comment by alastairmatheson** [comment]
Thanks, merged.
