### ISSUE TITLE
Remove old dashboard code

### ISSUE THREAD

**Issue by alastairmatheson** [PHSKC-APDE/Housing#30]
https://github.com/PHSKC-APDE/Housing/blob/main/analyses/dashboard/pha_dashboard_analyses.R  and https://github.com/PHSKC-APDE/Housing/blob/main/analyses/dashboard/pha_dashboard_analyses_qa.sql are out of date and should be deleted

**Comment by dcolombara** [comment]
addressed with commit e506cfcfafae5eb13d6902553fe6f40831041570
