### ISSUE TITLE
New voucher types not being classified

### ISSUE THREAD

**Issue by alastairmatheson** [PHSKC-APDE/Housing#32]
I noticed a decent chunk of SHA recipients who have HCV as their major_prog, TBV as their prog_type, but NA for vouch_final_type. This is impacting 5,149 rows out of 15,739 with SHA/HCV/TBV.

I haven't explored in great detail, but for the one individual I examined, they had some new vouch_type values in the 2022 data. Specifically, id_hash 6DAEE12F0BB5067AC9D5C753C5A2F3CD31E9E6958A2D66894BB6851B0C143B14 has 'No Voucher' and 'TENANT BASED' as values.

I suggest updating code here to include these options as values that lead to 'GENERAL TENANT-BASED VOUCHER':
https://github.com/PHSKC-APDE/Housing/blob/2fec2837b3f21a7d01eb8511ca1a71ff14cb757f/etl/stage/load_stage_pha_timevar.R#L158

And possible adding checks for new vouch_type values that need to be categorized.

**Comment by alastairmatheson** [comment]
I also see a few hundred rows in KCHA with missing vouch_type_final. The few I checked have 'EHV' as their vouch_type, which also needs to be accounted for.

**Comment by dcolombara** [comment]
moved issue to housing_etl repo
